### PR TITLE
Automatically obtain ENDF files from the web

### LINKED ISSUE #1: Automate ENDF retrieval.
The ENDF database has dependable links to zip-files containing the data, together with SHA1 sums. We can automate:
- downloading the zip files
- checking SHA1 keys
- access contents without physically unpacking

### PR DESCRIPTION
**Pull request by slokhorst**
Fixes #1

### CODE REVIEW

**Comment by lvkessel** [comment]
It seems you forgot to commit a `data/endf_sources.json` file,

**Comment by slokhorst** [comment]
It should be there, at `cstool/data/endf_sources.json`:
commit screenshot

If it doesn't work, maybe reinstalling the package (`pip install -e -U .`) fixes it?

**Comment by lvkessel** [comment]
The file is there, my bad. I was looking in the wrong `data/` folder (not the one in `cstool/`.

When I try to run this branch, I get an error in the json module. Full stack trace is:
````
  File "examples/cs.py", line 154, in <module>
    shells = ionization_shells(s)
  File "/xxx/cstool/ionization.py", line 76, in ionization_shells
    data = _ionization_shells(element.Z)
  File "/xxx/cstool/ionization.py", line 67, in _ionization_shells
    sources = obtain_endf_files()
  File "/xxx/cstool/ionization.py", line 42, in obtain_endf_files
    sources = json.loads(resource_string(__name__, 'data/endf_sources.json'))
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
````

When I could not find the file myself, I figured that must have been what caused it, but I was wrong -- after moving the file I get a `FileNotFoundError`. But something else is definitely still wrong.

I got this error after a completely clean installation, in a fresh virtual python environment.

**Comment by slokhorst** [comment]
Strange, I didn't have that. Maybe because I run a different Python version.

Does ce86720 fix it for you?

**Comment by lvkessel** [comment]
Yeah, that seems to fix it. Strange that this is necessary though.

The one further comment I have is that the `obtain_endf_files()` function does not check if the connection to the server succeeds when downloading. If the user has no active internet connection, or the server is down, file removed or whatever, the program will simply crash. A nice error message before crashing would be more user-friendly and easier to debug.

After that, I think it's OK to merge this.

**Comment by slokhorst** [comment]
Thanks for the feedback!

**Pull request merged**
